import logging; LOGGER = logging.getLogger(__name__)
import torch

from devices import DEVICE
import models

from training import ImageTrainertemplate

class AdvancedAdversarialTrainer(ImageTrainertemplate):
    def train_epoch(self,epoch:int) -> None:
        self.train_auto_encoder_epoch(epoch)
        self.train_discriminator_epoch(epoch)

        self.epoch_bar.set_postfix({
            "Loss: ae:":f"{self.auto_encoder_avg_loss:.4f}",
            "di:":f"{self.discriminator_avg_loss:.4f}"
        })

    def create_optimizers_and_critereons(self) -> None:
        self.reconstruction_loss_mult = 1.0
        self.adversarial_loss_mult = 0.02

        self.optimizer_auto_encoder  = torch.optim.Adam(self.model.model_auto_encoder.parameters(),  lr=self.learn_rate)
        self.optimizer_discriminator = torch.optim.Adam(self.model.model_discriminator.parameters(), lr=self.learn_rate)

        self.reconstruction_criterion = torch.nn.L1Loss()
        self.adversarial_criterion    = torch.nn.BCEWithLogitsLoss()
    
    def train_auto_encoder_epoch(self, epoch) -> None:
        self.freezer(fase_is_encoder=True)

        running_loss = 0.0
        for batch in self.data_loader:
            transformed_batch = self.transform_batch(batch)
            
            # Forward pass (now returns latent_z AND reconstructed image)
            latent_z, reconstructed_batch = self.model.model_auto_encoder(transformed_batch)
            loss = self.calculate_auto_encoder_loss(transformed_batch, reconstructed_batch, latent_z)

            # Backward pass
            self.model.model_auto_encoder.zero_grad()
            loss.backward()
            self.optimizer_auto_encoder.step()

            running_loss += loss.item()
        
        self.auto_encoder_avg_loss = running_loss / len(self.data_loader)
    
    def train_discriminator_epoch(self, epoch) -> None:
        self.freezer(fase_is_encoder=False)

        running_loss = 0.0
        for batch in self.data_loader:
            transformed_batch = self.transform_batch(batch)
            batch_size = transformed_batch.size(0)

            # ---------------------------------------------
            # Train on "Real" data (Sampled from Gaussian Prior)
            # ---------------------------------------------
            real_z = torch.randn(batch_size, self.model.latent_dim).to(DEVICE)
            predicted_real = self.model.model_discriminator(real_z)
            correct_prediction_real = torch.ones_like(predicted_real).to(DEVICE) # 1 = Gaussian prior
            loss_real = self.adversarial_criterion(predicted_real, correct_prediction_real)

            # ---------------------------------------------
            # Train on "Fake" data (Generated by the Encoder)
            # ---------------------------------------------
            # Detach so we don't calculate gradients for the autoencoder here
            latent_z, _ = self.model.model_auto_encoder(transformed_batch) 
            fake_z = latent_z.detach() 
            
            predicted_fake = self.model.model_discriminator(fake_z)
            correct_prediction_fake = torch.zeros_like(predicted_fake).to(DEVICE) # 0 = Encoder's output
            loss_fake = self.adversarial_criterion(predicted_fake, correct_prediction_fake)

            total_loss = (loss_real + loss_fake) * 0.5

            # Backward pass
            self.optimizer_discriminator.zero_grad()
            total_loss.backward()
            self.optimizer_discriminator.step()

            running_loss += total_loss.item()
        
        self.discriminator_avg_loss = running_loss / len(self.data_loader)
    
    def calculate_auto_encoder_loss(self, original_batch, reconstructed_batch, latent_z):
        # 1. Image quality (Pixel-to-pixel comparison)
        reconstruction_loss = self.reconstruction_criterion(reconstructed_batch, original_batch)

        # 2. Latent distribution realism (Discriminator score on z)
        discriminator_predictions = self.model.model_discriminator(latent_z)
        # The encoder wants the discriminator to think 'z' is from the true Gaussian prior (1s)
        target_labels = torch.ones_like(discriminator_predictions).to(DEVICE) 
        adversarial_loss = self.adversarial_criterion(discriminator_predictions, target_labels)

        # Combine them
        loss = (reconstruction_loss * self.reconstruction_loss_mult) + (adversarial_loss * self.adversarial_loss_mult)
        return loss
 
    def load_models(self) -> None:
        """
        Create the neural nets
        """        
        self.model = models.AdvancedAdversarialNetwork()
    
    def freezer(self, fase_is_encoder: bool) -> None:
        """
        Freezes and unfreezes paemters of the auto encoder / discirminattor respecitvly

        Args:
            fase_is_encoder (bool): If encoder then it will freeze the discirmntor and ...
        """        
        if fase_is_encoder:
            # Freeze discriminator / Unfreeze autoencoder
            self.model.model_discriminator.eval()
            for param in self.model.model_discriminator.parameters():
                param.requires_grad = False
                
            self.model.model_auto_encoder.train(True)
            for param in self.model.model_auto_encoder.parameters():
                param.requires_grad = True
        else:
            # Freeze autoencoder / Unfreeze discriminator
            self.model.model_auto_encoder.eval()
            for param in self.model.model_auto_encoder.parameters():
                param.requires_grad = False
                
            self.model.model_discriminator.train(True)
            for param in self.model.model_discriminator.parameters():
                param.requires_grad = True